markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: panxw
author: ""
email: winfirm#163.com
name: "潘学文个人博客"
url: http://www.panxw.com
domain: www.panxw.com
all_categories: [
["android", "中国航天","/posts/android.html"], 
["program", "国际航天","/posts/program.html"],
["web", "发射计划","/posts/web.html"], 
["linux", "太空科技","/posts/linux.html"],
["read", "宇航科学","/posts/read.html"], 
["other", "FAQs","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
